# Generated by Django 4.2.13 on 2024-05-28 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color_code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPack',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('item_id', models.ManyToManyField(to='store_app.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('color_code', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPackColor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.color')),
                ('item_pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.itempack')),
            ],
        ),
        migrations.AddField(
            model_name='itempack',
            name='packaging_id',
            field=models.ManyToManyField(to='store_app.packaging'),
        ),
    ]
