# Generated by Django 4.2.13 on 2024-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='something@gmail.com', max_length=100, unique=True),
        ),
    ]
