# Generated by Django 4.2.13 on 2024-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.FileField(default='/home/ali/Documents/thread_store/store_app/images/image.jpg', upload_to=''),
        ),
    ]
