# Generated by Django 4.2.13 on 2024-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_remove_item_img_alter_item_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
