# Generated by Django 4.2.13 on 2024-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_item_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.FileField(default='dummy', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
    ]
