# Generated by Django 4.2.13 on 2024-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.URLField(max_length=300),
        ),
    ]
