# Generated by Django 4.2.13 on 2024-06-04 19:06

from django.db import migrations, models
import store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_alter_item_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img_url',
        ),
        migrations.CreateModel(
            name='ImagesItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alt_text', models.CharField(max_length=255)),
                ('img_url', models.FileField(max_length=255, upload_to=store_app.models.assign)),
                ('order_no', models.IntegerField()),
                ('item_id', models.ManyToManyField(to='store_app.item')),
            ],
        ),
    ]
